server:
    port: 9090
spring:
    application:
        name: CRUD.JPA.PostgreSQL
    datasource:
        url: jdbc:postgresql://localhost:5431/crudJpaPostgreSQL
        username: postgres
        password: progpasci
        driver-class-name: org.postgresql.Driver
    jpa:
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true